---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
  synced_folders:
    - ["", "/tmp/build"]

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
  - name: centos-6.5-i386
  - name: ubuntu-14.04
  - name: ubuntu-14.10-i386
  - name: centos-5.11
  - name: ubuntu-10.04
  - name: ubuntu-12.04

suites:
  - name: build
    excludes:
      - centos-6.5-i386
      - ubuntu-14.04
      - ubuntu-14.10-i386
      - centos-5.11
      - ubuntu-10.04
      - ubuntu-12.04
    run_list:
      - recipe[uchiwa-build]
    attributes:
      uchiwa-build:
        uchiwa_version: <%= ENV['UCHIWA_VERSION'] %>
        build_number: <%= ENV['BUILD_NUMBER'] %>
        git: <%= ENV['UCHIWA_GIT'] %>
  - name: test
    run_list:
      - recipe[uchiwa-build::test]
    attributes:
      uchiwa-build:
        uchiwa_version: <%= ENV['UCHIWA_VERSION'] %>
        build_number: <%= ENV['BUILD_NUMBER'] %>
        git: <%= ENV['UCHIWA_GIT'] %>
  - name: s3_upload
    excludes:
      - centos-6.5-i386
      - centos-6.5
      - ubuntu-14.04
      - ubuntu-14.10-i386
      - centos-5.11
      - ubuntu-10.04
    run_list:
      - recipe[uchiwa-build::s3_upload]
    attributes:
      uchiwa-build:
        uchiwa_version: <%= ENV['UCHIWA_VERSION'] %>
        build_number: <%= ENV['BUILD_NUMBER'] %>
        s3_bucket: <%= ENV['S3_BUCKET'] %>
        s3_gpg_sign: <%= ENV['S3_GPG_SIGN'] %>
        s3_amazon_access_key_id: <%= ENV['S3_AMAZON_ACCESS_KEY_ID'] %>
        s3_amazon_secret_access_key: <%= ENV['S3_AMAZON_SECRET_ACCESS_KEY'] %>
        s3_debian_codename: <%= ENV['S3_DEBIAN_CODENAME'] %>
